In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [ ]:
Populationdf = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/population excel.xlsx')
df

    Year  Yearly % \nChange  ...  India\nGlobal Rank  Population
0   2050               0.23  ...                   1  1639176033
1   2045               0.35  ...                   1  1620619200
2   2040               0.50  ...                   1  1592691513
3   2035               0.66  ...                   1  1553723810
4   2030               0.80  ...                   1  1503642322
5   2025               0.92  ...                   2  1445011620
6   2020               1.04  ...                   2  1380004385
7   2019               1.02  ...                   2  1366417754
8   2018               1.04  ...                   2  1352642280
9   2017               1.07  ...                   2  1338676785
10  2016               1.10  ...                   2  1324517249
11  2015               1.20  ...                   2  1310152403
12  2010               1.47  ...                   2  1234281170
13  2005               1.67  ...                   2  1147609927
14  2000               1.85  ...                   2  1056575549
15  1995               1.99  ...                   2   963922588
16  1990               2.17  ...                   2   873277798
17  1985               2.33  ...                   2   784360008
18  1980               2.32  ...                   2   698952844
19  1975               2.33  ...                   2   623102897
20  1970               2.15  ...                   2   555189792
21  1965               2.07  ...                   2   499123324
22  1960               1.91  ...                   2   450547679
23  1955               1.72  ...                   2   409880595

[24 rows x 13 columns]

In [ ]:
print(df['Migrants (net)'].median())

-414772.0

In [ ]:
df['Migrants (net)'].fillna(df['Migrants (net)'].median(), inplace=True)
df

/tmp/ipykernel_857/2852011191.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Migrants (net)'].fillna(df['Migrants (net)'].median(), inplace=True)

    Year  Yearly % \nChange  ...  India\nGlobal Rank  Population
0   2050               0.23  ...                   1  1639176033
1   2045               0.35  ...                   1  1620619200
2   2040               0.50  ...                   1  1592691513
3   2035               0.66  ...                   1  1553723810
4   2030               0.80  ...                   1  1503642322
5   2025               0.92  ...                   2  1445011620
6   2020               1.04  ...                   2  1380004385
7   2019               1.02  ...                   2  1366417754
8   2018               1.04  ...                   2  1352642280
9   2017               1.07  ...                   2  1338676785
10  2016               1.10  ...                   2  1324517249
11  2015               1.20  ...                   2  1310152403
12  2010               1.47  ...                   2  1234281170
13  2005               1.67  ...                   2  1147609927
14  2000               1.85  ...                   2  1056575549
15  1995               1.99  ...                   2   963922588
16  1990               2.17  ...                   2   873277798
17  1985               2.33  ...                   2   784360008
18  1980               2.32  ...                   2   698952844
19  1975               2.33  ...                   2   623102897
20  1970               2.15  ...                   2   555189792
21  1965               2.07  ...                   2   499123324
22  1960               1.91  ...                   2   450547679
23  1955               1.72  ...                   2   409880595

[24 rows x 13 columns]

In [ ]:
lr = linear_model.LinearRegression()

# List of columns that are expected to be numerical but might contain strings with commas
numerical_cols_to_clean = ['Population', 'Urban Population', 'World Population']

for col in numerical_cols_to_clean:
    # Convert column to string, remove commas, then convert to numeric, coercing errors to NaN
    df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', ''), errors='coerce')

# Drop rows where any of the cleaned numerical columns might have become NaN due to 'coerce'
df.dropna(subset=numerical_cols_to_clean, inplace=True)

lr.fit(df[['Year', 'Yearly % \nChange', 'Yearly\nChange', 'Migrants (net)', 'Median Age',  'Fertility Rate', 'Density (P/Km²)', 'Urban\nPop %', 'Urban Population', 'World Population']], df.Population)

LinearRegression()

In [ ]:
lr.predict( [ [ 2045,0.35,5585537,-414772.0, 36.6, 2.24, 545, 50.1, 811749463, 9481803274 ]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([1.62013907e+09])

In [ ]:
lr.coef_

array([ 2.01227990e+06, -2.90854384e+07,  1.69463856e+00,  1.13170103e+00,
        2.57529522e+06,  7.81154254e+06,  2.92313157e+06,  2.56350514e+06,
       -2.69481569e-01, -1.40413418e-02])

In [ ]:
lr.intercept_

np.float64(-3975192695.0829983)

In [21]:
population = (2.01227990e+06 * 2045 + -2.90854384e+07 * 0.35 +  1.69463856e+00 * 5585537 +  1.13170103e+00 * 414772.0 +
              2.57529522e+06 * 36.6 +  7.81154254e+06 * 2.24 + 2.92313157e+06 * 545 + 2.56350514e+06 * 50.1 +
              -2.69481569e-01 * 811749463 + -1.40413418e-02 * 9481803274 + -3975192695.0829983)
print(population)

1621077875.1859827

In [22]:
lr.score(df[['Year', 'Yearly % \nChange', 'Yearly\nChange', 'Migrants (net)', 'Median Age',  'Fertility Rate', 'Density (P/Km²)', 'Urban\nPop %', 'Urban Population', 'World Population']], df.Population)

0.9999987859621557